# Generated by Django 4.2.7 on 2024-01-29 01:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hotel_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ImageField(blank=True, upload_to=hotel_app.models.amenity_image_upload)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('phone_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('hotel_rating', models.FloatField(default=0.0)),
                ('image', models.ImageField(blank=True, upload_to=hotel_app.models.hotel_image_upload)),
                ('hotel_type', models.CharField(choices=[('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('7', '7')], max_length=5)),
                ('amenities', models.ManyToManyField(to='hotel_app.amenity')),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('suite', 'suite')], max_length=10)),
                ('image', models.ImageField(blank=True, upload_to=hotel_app.models.room_image_upload)),
                ('capacity', models.IntegerField(default=0)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=400)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', to='hotel_app.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewsAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=300)),
                ('rating', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_reviews', to='hotel_app.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=55)),
                ('last_name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('room_type', models.CharField(choices=[('single', 'single'), ('double', 'double'), ('suite', 'suite')], max_length=10)),
                ('check_in_date', models.DateTimeField()),
                ('check_out_date', models.DateTimeField()),
                ('number_of_guests', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_day', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('confirmed', 'confirmed'), ('pending', 'pending'), ('cancelled', 'cancelled')], max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('hotel_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservations', to='hotel_app.hotelroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reservations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
